//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DAO.DataModels
{
	/// <summary>
	/// Database       : FBDB
	/// Data Source    : localhost
	/// Server Version : WI-V2.5.7.27050 Firebird 2.5/tcp (ARTEX-TK)/P12
	/// </summary>
	public partial class FBDBDB : LinqToDB.Data.DataConnection
	{
		public ITable<AritSlmBlokada>        AritSlmBlokadas        { get { return this.GetTable<AritSlmBlokada>(); } }
		public ITable<AritSlmDostawaView>    AritSlmDostawaViews    { get { return this.GetTable<AritSlmDostawaView>(); } }
		public ITable<AritSlmMagazynView>    AritSlmMagazynViews    { get { return this.GetTable<AritSlmMagazynView>(); } }
		public ITable<AritSlmMiejscaSklView> AritSlmMiejscaSklViews { get { return this.GetTable<AritSlmMiejscaSklView>(); } }
		public ITable<AritSlmRackView>       AritSlmRackViews       { get { return this.GetTable<AritSlmRackView>(); } }
		public ITable<AritSlmSprzUserMag>    AritSlmSprzUserMags    { get { return this.GetTable<AritSlmSprzUserMag>(); } }
		public ITable<AritSlmUzytkownik>     AritSlmUzytkowniks     { get { return this.GetTable<AritSlmUzytkownik>(); } }
		public ITable<DOSTAWA>               Dostawas               { get { return this.GetTable<DOSTAWA>(); } }

		public FBDBDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public FBDBDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public FBDBDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public FBDBDB(LinqToDBConnectionOptions<FBDBDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="SYSDBA", Name="ARIT_SLM_BLOKADA")]
	public partial class AritSlmBlokada
	{
		[Column("ID_MIEJSCESKL"), PrimaryKey, NotNull] public int      IdMiejsceskl { get; set; } // integer
		[Column("DATA_BLOKADY"),              NotNull] public DateTime DataBlokady  { get; set; } // timestamp
	}

	[Table(Schema="SYSDBA", Name="ARIT_SLM_DOSTAWA_VIEW", IsView=true)]
	public partial class AritSlmDostawaView
	{
		[Column("ID_MIEJSCESKL"),          Nullable] public int?      IdMiejsceskl       { get; set; } // integer
		[Column("ID_DOSTAWA"),             Nullable] public int?      IdDostawa          { get; set; } // integer
		[Column("ID_POZ"),                 Nullable] public int?      IdPoz              { get; set; } // integer
		[Column("ID_KARTOTEKA"),           Nullable] public int?      IdKartoteka        { get; set; } // integer
		[Column(),                         Nullable] public string    KODMSKL            { get; set; } // varchar(35)
		[Column(),                         Nullable] public string    INDEKS             { get; set; } // varchar(40)
		[Column(),                         Nullable] public string    NAZWASKR           { get; set; } // varchar(35)
		[Column(),                         Nullable] public DateTime? TPS                { get; set; } // timestamp
		[Column(),                         Nullable] public string    PARTIA             { get; set; } // varchar(60)
		[Column("WAGA_NETTO"),          NotNull    ] public decimal   WagaNetto          { get; set; } // numeric(18,4)
		[Column("WAGA_BRUTTO"),            Nullable] public string    WagaBrutto         { get; set; } // varchar(35)
		[Column("DATA_UBOJU"),             Nullable] public string    DataUboju          { get; set; } // varchar(35)
		[Column("DATA_MROZENIA"),          Nullable] public string    DataMrozenia       { get; set; } // varchar(35)
		[Column("RODZAJ_OPAKOWANIA"),      Nullable] public string    RodzajOpakowania   { get; set; } // varchar(35)
		[Column("ILOSC_OPAKOWAN"),         Nullable] public string    IloscOpakowan      { get; set; } // varchar(35)
		[Column("RODZAJ_PALETY"),          Nullable] public string    RodzajPalety       { get; set; } // varchar(35)
		[Column("TEMP_PRZECHOWYWANIA"),    Nullable] public string    TempPrzechowywania { get; set; } // varchar(35)
	}

	[Table(Schema="SYSDBA", Name="ARIT_SLM_MAGAZYN_VIEW", IsView=true)]
	public partial class AritSlmMagazynView
	{
		[Column("ID_MAGAZYN"),  Nullable] public int?   IdMagazyn { get; set; } // integer
		[Column(),              Nullable] public int?   NRMAG     { get; set; } // integer
		[Column(),              Nullable] public string NAZWAMAG  { get; set; } // varchar(40)
		[Column("KOD_MSC_SKL"), Nullable] public string KodMscSkl { get; set; } // varchar(10)
	}

	[Table(Schema="SYSDBA", Name="ARIT_SLM_MIEJSCA_SKL_VIEW", IsView=true)]
	public partial class AritSlmMiejscaSklView
	{
		[Column("ID_MIEJSCESKL"), Nullable] public int?   IdMiejsceskl { get; set; } // integer
		[Column("ID_KARTOTEKA"),  Nullable] public int?   IdKartoteka  { get; set; } // integer
		[Column(),                Nullable] public string INDEKS       { get; set; } // varchar(40)
		[Column(),                Nullable] public string NAZWADL      { get; set; } // varchar(360)
		[Column(),                Nullable] public string KODMSKL      { get; set; } // varchar(35)
		[Column("KOD_MAG"),       Nullable] public string KodMag       { get; set; } // varchar(35)
		[Column(),                Nullable] public string REGAL        { get; set; } // varchar(35)
		[Column(),                Nullable] public int?   POZIOM       { get; set; } // integer
		[Column(),                Nullable] public int?   KOLUMNA      { get; set; } // integer
		[Column(),                Nullable] public int?   BLOKADA      { get; set; } // integer
	}

	[Table(Schema="SYSDBA", Name="ARIT_SLM_RACK_VIEW", IsView=true)]
	public partial class AritSlmRackView
	{
		[Column("KOD_MAG"),      Nullable] public string KodMag      { get; set; } // varchar(35)
		[Column("ILOSC_MIEJSC"), Nullable] public int?   IloscMiejsc { get; set; } // integer
		[Column(),               Nullable] public int?   ZAJETYCH    { get; set; } // integer
		[Column(),               Nullable] public string REGAL       { get; set; } // varchar(35)
	}

	[Table(Schema="SYSDBA", Name="ARIT_SLM_SPRZ_USER_MAG")]
	public partial class AritSlmSprzUserMag
	{
		[Column("ID_ARIT_SLM_UZYTKOWNIK"), PrimaryKey(0), NotNull] public int IdAritSlmUzytkownik { get; set; } // integer
		[Column("ID_MAGAZYN"),             PrimaryKey(1), NotNull] public int IdMagazyn           { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_ARIT_SLM_SPRZ_USER_MAG_1 (SYSDBA.ARIT_SLM_UZYTKOWNIK)
		/// </summary>
		[Association(ThisKey="IdAritSlmUzytkownik", OtherKey="IdAritSlmUzytkownik", CanBeNull=false)]
		public AritSlmUzytkownik ARITSLMSPRZUSERMAG { get; set; }

		#endregion
	}

	[Table(Schema="SYSDBA", Name="ARIT_SLM_UZYTKOWNIK")]
	public partial class AritSlmUzytkownik
	{
		[Column("ID_ARIT_SLM_UZYTKOWNIK"), PrimaryKey,  NotNull] public int    IdAritSlmUzytkownik { get; set; } // integer
		[Column(),                            Nullable         ] public string LOGIN               { get; set; } // varchar(50)
		[Column(),                            Nullable         ] public string HASLO               { get; set; } // varchar(360)
		[Column(),                            Nullable         ] public short? AKTYWNY             { get; set; } // smallint

		#region Associations

		/// <summary>
		/// FK_ARIT_SLM_SPRZ_USER_MAG_1_BackReference (SYSDBA.ARIT_SLM_SPRZ_USER_MAG)
		/// </summary>
		[Association(ThisKey="IdAritSlmUzytkownik", OtherKey="IdAritSlmUzytkownik", CanBeNull=true)]
		public IEnumerable<AritSlmSprzUserMag> Aritslmsprzusermags { get; set; }

		#endregion
	}

	[Table(Schema="SYSSTR", Name="DOSTAWA")]
	public partial class DOSTAWA
	{
		[Column("ID_DOSTAWA"),        PrimaryKey,  NotNull] public int       IdDostawa         { get; set; } // integer
		[Column("ID_POZ"),                         NotNull] public int       IdPoz             { get; set; } // integer
		[Column("ID_KARTOTEKA"),                   NotNull] public int       IdKartoteka       { get; set; } // integer
		[Column("ID_MAGAZYN"),                     NotNull] public int       IdMagazyn         { get; set; } // integer
		[Column("ID_POZZRODLA"),                   NotNull] public int       IdPozzrodla       { get; set; } // integer
		[Column(),                                 NotNull] public decimal   ILOSCDOST         { get; set; } // numeric(18,4)
		[Column(),                                 NotNull] public decimal   CENAZAKDOST       { get; set; } // numeric(18,4)
		[Column(),                                 NotNull] public decimal   WARTDOST          { get; set; } // numeric(18,4)
		[Column(),                                 NotNull] public decimal   STANROZCH         { get; set; } // numeric(18,4)
		[Column(),                                 NotNull] public decimal   STANAKTDOST       { get; set; } // numeric(18,4)
		[Column(),                                 NotNull] public decimal   WARTAKTDOST       { get; set; } // numeric(18,4)
		[Column(),                                 NotNull] public short     BLOKADA           { get; set; } // smallint
		[Column(),                                 NotNull] public short     ZREALIZOWANA      { get; set; } // smallint
		[Column(),                       Nullable         ] public string    NRDOSTAWY         { get; set; } // varchar(60)
		[Column(),                       Nullable         ] public DateTime? DATAWAZNOSCI      { get; set; } // timestamp
		[Column(),                       Nullable         ] public DateTime? DATADOK           { get; set; } // timestamp
		[Column("ID_MIEJSCESKL"),        Nullable         ] public int?      IdMiejsceskl      { get; set; } // integer
		[Column("ID_ROZCHDOST"),         Nullable         ] public int?      IdRozchdost       { get; set; } // integer
		[Column(),                                 NotNull] public DateTime  DATADOSTAWY       { get; set; } // timestamp
		[Column("SZAC_ZYSK"),            Nullable         ] public decimal?  SzacZysk          { get; set; } // numeric(8,4)
		[Column("SZAC_MARZA"),           Nullable         ] public decimal?  SzacMarza         { get; set; } // numeric(8,4)
		[Column("SZAC_NARZUT"),          Nullable         ] public decimal?  SzacNarzut        { get; set; } // numeric(8,4)
		[Column("ID_PARTIAZP"),          Nullable         ] public int?      IdPartiazp        { get; set; } // integer
		[Column(),                       Nullable         ] public DateTime? DATAREALIZACJI    { get; set; } // timestamp
		[Column(),                                 NotNull] public decimal   STANZAREZERWOWANY { get; set; } // numeric(18,4)
		[Column(),                       Nullable         ] public decimal?  STANDOSTEPNY      { get; set; } // decimal(8,4)
		[Column(),                                 NotNull] public short     ZERUJSTANAKT      { get; set; } // smallint
		[Column("BLOKADA_LOG"),                    NotNull] public short     BlokadaLog        { get; set; } // smallint
		[Column("ID_DANEDOSTAWALOG"),              NotNull] public int       IdDanedostawalog  { get; set; } // integer
		[Column(),                                 NotNull] public int       STATUSW           { get; set; } // integer
		[Column(),                       Nullable         ] public short?    STATUS            { get; set; } // smallint
	}

	public static partial class FBDBDBStoredProcedures
	{
		#region AritSlmEditDostawa

		public static int AritSlmEditDostawa(this FBDBDB dataConnection, int? ID_DOSTAWA, DateTime? TPS, string PARTIA, string DATA_UBOJU, string DATA_MROZENIA, string TEMP_PRZECHOWYWANIA)
		{
			var parameters = new []
			{
				new DataParameter("ID_DOSTAWA",          ID_DOSTAWA,          LinqToDB.DataType.Int32)
				{
					Size = 4
				},
				new DataParameter("TPS",                 TPS,                 LinqToDB.DataType.DateTime)
				{
					Size = 8
				},
				new DataParameter("PARTIA",              PARTIA,              LinqToDB.DataType.NVarChar)
				{
					Size = 60
				},
				new DataParameter("DATA_UBOJU",          DATA_UBOJU,          LinqToDB.DataType.NVarChar)
				{
					Size = 35
				},
				new DataParameter("DATA_MROZENIA",       DATA_MROZENIA,       LinqToDB.DataType.NVarChar)
				{
					Size = 35
				},
				new DataParameter("TEMP_PRZECHOWYWANIA", TEMP_PRZECHOWYWANIA, LinqToDB.DataType.NVarChar)
				{
					Size = 35
				}
			};

			return dataConnection.ExecuteProc("ARIT_SLM_EDIT_DOSTAWA", parameters);
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static AritSlmBlokada Find(this ITable<AritSlmBlokada> table, int IdMiejsceskl)
		{
			return table.FirstOrDefault(t =>
				t.IdMiejsceskl == IdMiejsceskl);
		}

		public static AritSlmSprzUserMag Find(this ITable<AritSlmSprzUserMag> table, int IdAritSlmUzytkownik, int IdMagazyn)
		{
			return table.FirstOrDefault(t =>
				t.IdAritSlmUzytkownik == IdAritSlmUzytkownik &&
				t.IdMagazyn           == IdMagazyn);
		}

		public static AritSlmUzytkownik Find(this ITable<AritSlmUzytkownik> table, int IdAritSlmUzytkownik)
		{
			return table.FirstOrDefault(t =>
				t.IdAritSlmUzytkownik == IdAritSlmUzytkownik);
		}

		public static DOSTAWA Find(this ITable<DOSTAWA> table, int IdDostawa)
		{
			return table.FirstOrDefault(t =>
				t.IdDostawa == IdDostawa);
		}
	}
}
